header:
  license:
    spdx-id: MPL-2.0

    content: |
      This Source Code Form is subject to the terms of the Mozilla Public
      License, v. 2.0. If a copy of the MPL was not distributed with this
      file, You can obtain one at https://mozilla.org/MPL/2.0/.
  paths:
    - '**/*.js'
    - '**/*.rs'
  paths-ignore:
    - '**/generated/*.rs'
    - 'parse-rfd/parser/dist/index.js'

  comment: on-failure