[package]
name = "rfd-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
dirs = { workspace = true }
oauth2 = { workspace = true }
progenitor-client = { workspace = true }
reqwest = { workspace = true }
rfd-sdk = { path = "../rfd-sdk" }
serde = { workspace = true }
serde_json = { workspace = true }
tabwriter = { workspace = true }
textwrap = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
toml = { workspace = true }
uuid = { workspace = true, features = ["serde"] }