name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1
        with:
          command: build
          args: --release
        env:
          RUSTFLAGS: "--cfg tracing_unstable"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/rfd-api
            target/release/rfd-cli
            target/release/rfd-processor
            target/release/rfd-redirect